# Generated by Django 5.1.3 on 2025-02-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Pregunta')),
                ('tipo_respuesta', models.IntegerField(verbose_name='tipo de preguntas')),
                ('sig_pregunta', models.JSONField(blank=True, null=True, verbose_name='siguiente pregunta')),
                ('tipo_cuestionario', models.IntegerField(verbose_name='tipo cuestionario')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'db_table': 'preguntas',
            },
        ),
        migrations.CreateModel(
            name='RespuestaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(verbose_name='usuario')),
                ('id_cuestionario', models.IntegerField(verbose_name='cuestionario')),
                ('id_pregunta', models.IntegerField(verbose_name='no. pregunta')),
                ('id_respuesta', models.IntegerField(verbose_name='respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'respuestas',
            },
        ),
    ]
