# Generated by Django 5.1.3 on 2025-03-14 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Pregunta')),
                ('tipo_respuesta', models.IntegerField(verbose_name='tipo de preguntas')),
                ('sig_pregunta', models.JSONField(blank=True, null=True, verbose_name='siguiente pregunta')),
                ('tipo_cuestionario', models.IntegerField(verbose_name='tipo cuestionario')),
                ('imagen_grupal', models.BooleanField(null=True, verbose_name='imagen grupal')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Activo')),
                ('no_pregunta', models.IntegerField(blank=True, null=True, verbose_name='No. Pregunta')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'db_table': 'preguntas',
            },
        ),
        migrations.CreateModel(
            name='RespuestaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(verbose_name='usuario')),
                ('id_cuestionario', models.IntegerField(verbose_name='cuestionario')),
                ('no_pregunta', models.IntegerField(verbose_name='no. pregunta')),
                ('id_respuesta', models.IntegerField(verbose_name='respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'respuestas',
            },
        ),
        migrations.CreateModel(
            name='ImagenRespuestaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='nombre imagen')),
                ('imagen', models.ImageField(upload_to='imagen_respuesta/')),
                ('id_respuesta', models.IntegerField(null=True, verbose_name='ID de respuesta')),
                ('pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='cuestionario.preguntamodel')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imagenes',
                'db_table': 'imagenes',
            },
        ),
    ]
