# Generated by Django 5.1.3 on 2024-12-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntamodel',
            options={'verbose_name': 'pregunta', 'verbose_name_plural': 'preguntas'},
        ),
        migrations.AddField(
            model_name='preguntamodel',
            name='tipo_cuestionario',
            field=models.IntegerField(default=1, verbose_name='tipo cuestionario'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='preguntamodel',
            table='preguntas',
        ),
    ]
