# Generated by Django 5.1.3 on 2025-04-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenRespuestaModel',
        ),
    ]
