# Generated by Django 5.1.3 on 2024-12-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0002_alter_preguntamodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntamodel',
            name='sig_pregunta',
            field=models.JSONField(verbose_name='siguiente pregunta'),
        ),
    ]
