# Generated by Django 5.1.3 on 2024-11-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatCuestionarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_largo', models.CharField(max_length=30, verbose_name='Nombre Largo')),
                ('abreviacion', models.CharField(max_length=5, verbose_name='Nombre Corto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
                'db_table': 'catalogo_cuestionario',
            },
        ),
    ]
