# Generated by Django 5.1.3 on 2025-02-01 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatEstadoCivil',
        ),
    ]
