# Generated by Django 5.1.3 on 2025-01-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_catcuestionarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatFrecuencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_largo', models.CharField(max_length=30, verbose_name='Nombre Largo')),
                ('abreviacion', models.CharField(max_length=5, verbose_name='Nombre Corto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'frecuencia',
                'verbose_name_plural': 'frecuencias',
                'db_table': 'frecuencia',
            },
        ),
        migrations.CreateModel(
            name='CatOpcionMultiple',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_largo', models.CharField(max_length=30, verbose_name='Nombre Largo')),
                ('abreviacion', models.CharField(max_length=5, verbose_name='Nombre Corto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'opcion',
                'verbose_name_plural': 'opciones',
                'db_table': 'opcion',
            },
        ),
    ]
