# Generated by Django 5.1.3 on 2025-02-17 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_delete_catestadocivil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.catniveleducativo', verbose_name='Nivel Educativo')),
                ('poblacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.catpoblacion', verbose_name='Población')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.catsexo', verbose_name='Sexo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
