# Generated by Django 5.1.3 on 2025-03-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_datosgenerales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcuestionarios',
            name='nombre_largo',
            field=models.CharField(max_length=40, verbose_name='Nombre Largo'),
        ),
        migrations.AlterField(
            model_name='catfrecuencia',
            name='nombre_largo',
            field=models.CharField(max_length=40, verbose_name='Nombre Largo'),
        ),
        migrations.AlterField(
            model_name='catniveleducativo',
            name='nombre_largo',
            field=models.CharField(max_length=40, verbose_name='Nombre Largo'),
        ),
        migrations.AlterField(
            model_name='catopcionmultiple',
            name='nombre_largo',
            field=models.CharField(max_length=40, verbose_name='Nombre Largo'),
        ),
        migrations.AlterField(
            model_name='catpoblacion',
            name='nombre_largo',
            field=models.CharField(max_length=40, verbose_name='Nombre Largo'),
        ),
        migrations.AlterField(
            model_name='catsexo',
            name='nombre_largo',
            field=models.CharField(max_length=40, verbose_name='Nombre Largo'),
        ),
    ]
