# Generated by Django 5.1.3 on 2025-03-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_alter_catcuestionarios_nombre_largo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatOpcionMultipleEspecial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_largo', models.CharField(max_length=40, verbose_name='Nombre Largo')),
                ('abreviacion', models.CharField(max_length=5, verbose_name='Nombre Corto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'opción especial',
                'verbose_name_plural': 'opciones especiales',
                'db_table': 'opciones_especial',
            },
        ),
    ]
