# Generated by Django 5.1.3 on 2025-03-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_catopcionmultipleespecial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatIngresos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_largo', models.CharField(max_length=40, verbose_name='Nombre Largo')),
                ('abreviacion', models.CharField(max_length=5, verbose_name='Nombre Corto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'ingreso',
                'verbose_name_plural': 'ingresos',
                'db_table': 'ingresos',
            },
        ),
        migrations.CreateModel(
            name='CatSituacionLaboral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_largo', models.CharField(max_length=40, verbose_name='Nombre Largo')),
                ('abreviacion', models.CharField(max_length=5, verbose_name='Nombre Corto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'situación laboral',
                'verbose_name_plural': 'situaciones laborales',
                'db_table': 'situacion_laboral',
            },
        ),
    ]
