# Generated by Django 5.1.3 on 2025-02-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0003_datosgenerales'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Ingresos')),
                ('abreviacion', models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='CatSituacionLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Situación Laboral')),
                ('abreviacion', models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='DatosSocioeconomicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_generales', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogos.datosgenerales', verbose_name='Datos Generales')),
                ('ingresos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_socioeconomicos.catingresos', verbose_name='Ingreso')),
                ('situacion_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_socioeconomicos.catsituacionlaboral', verbose_name='Situación Laboral')),
            ],
        ),
    ]
