# Generated by Django 5.1.1 on 2024-09-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatIngresos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('abreviacion', models.CharField(max_length=5, verbose_name='Abreviación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Cantidad de ingresos',
                'db_table': 'cat_ingreso',
            },
        ),
        migrations.CreateModel(
            name='CatSituacionLaboral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('abreviacion', models.CharField(max_length=5, verbose_name='Abreviación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Situacion Laboral',
                'verbose_name_plural': 'Tipos de situacion laboral',
                'db_table': 'cat_situacion_laboral',
            },
        ),
    ]
