# Generated by Django 5.1.3 on 2025-03-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_socioeconomicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestasDatosgenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('situacion_laboral', models.IntegerField()),
                ('ingresos', models.IntegerField()),
                ('sexo', models.IntegerField()),
                ('poblacion', models.IntegerField()),
                ('nivel_educativo', models.IntegerField()),
            ],
            options={
                'db_table': 'respuestas_datos_generales',
            },
        ),
    ]
