# Generated by Django 5.1.1 on 2024-10-14 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'managed': True, 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='Usuarios',
        ),
    ]
