# Generated by Django 5.1.3 on 2025-01-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usermodel_options_alter_usermodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(verbose_name='id usuario')),
                ('cuestionarios', models.JSONField(verbose_name='Cuestionarios disponibles')),
            ],
            options={
                'verbose_name': 'progreso de usuario',
                'verbose_name_plural': 'progresos de usuario',
                'db_table': 'progreso_usuario',
            },
        ),
    ]
