# Generated by Django 5.1.5 on 2025-01-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_progresomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nombre_completo',
            field=models.CharField(default='Usuario Desconocido', max_length=255, verbose_name='Nombre completo'),
            preserve_default=False,
        ),
    ]
