# Generated by Django 5.1.1 on 2024-09-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('opcion', models.CharField(max_length=100, verbose_name='opción')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('cat_opciones', models.IntegerField(verbose_name='Respuestas')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('id_registro', models.IntegerField()),
            ],
        ),
    ]
