# Generated by Django 5.1.1 on 2024-09-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatFrecuencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Valor')),
                ('nombre', models.CharField(max_length=50, verbose_name='Frecuencia')),
                ('abvr', models.CharField(max_length=5, verbose_name='Abreviación')),
            ],
            options={
                'verbose_name': 'Respuesta Frecuencia',
                'verbose_name_plural': 'Respuestas Frecuencia',
                'db_table': 'cat_frecuencia',
            },
        ),
    ]
