# Generated by Django 5.1.1 on 2024-09-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatImagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Imagen')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'db_table': 'cat_imagen',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pregunta')),
                ('texto', models.TextField(verbose_name='Texto de la pregunta')),
                ('tipo_respuesta', models.IntegerField(verbose_name='Tipo de Respuesta')),
                ('grupo_imagen', models.BooleanField(default=False, verbose_name='¿Tiene grupo de imágenes?')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'pregunta',
            },
        ),
        migrations.AlterField(
            model_name='catfrecuencia',
            name='abvr',
            field=models.CharField(help_text='Escribe la abreviación del campo', max_length=5, verbose_name='Abreviación'),
        ),
        migrations.AlterField(
            model_name='catfrecuencia',
            name='nombre',
            field=models.CharField(help_text='Escribe el texto de la respuesta', max_length=50, verbose_name='Frecuencia'),
        ),
    ]
