# Generated by Django 5.1.1 on 2024-09-26 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0002_catimagen_pregunta_alter_catfrecuencia_abvr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatImagen',
        ),
    ]
