# Generated by Django 5.1.1 on 2024-09-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0003_delete_catimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatOpcion',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False, verbose_name='valor')),
                ('nombre_opcion', models.CharField(max_length=30, verbose_name='opción')),
                ('avbr', models.CharField(max_length=30, verbose_name='Abreviación')),
            ],
            options={
                'verbose_name': 'opción',
                'verbose_name_plural': 'opciones',
                'db_table': 'cat_opion',
            },
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='id_pregunta',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='valor'),
        ),
    ]
