# Generated by Django 5.1.1 on 2024-09-26 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0004_catopcion_alter_pregunta_id_pregunta'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catopcion',
            table='cat_opcion',
        ),
    ]
