# Generated by Django 5.1.1 on 2024-09-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0005_alter_catopcion_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaConsumo',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False, verbose_name='id pregunta')),
                ('respuestas', models.TextField(verbose_name='respuestas')),
            ],
            options={
                'verbose_name': 'respuesta de consumo',
                'verbose_name_plural': 'respuestas de consumo',
                'db_table': 'respuestas_consumo',
            },
        ),
    ]
