# Generated by Django 5.1.1 on 2024-09-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0006_respuestaconsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='pregunta',
            field=models.CharField(blank=True, max_length=50, verbose_name='Titulo de pregunta'),
        ),
    ]
