# Generated by Django 5.1.1 on 2024-09-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatEstadoCivil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('abreviacion', models.CharField(max_length=5, verbose_name='Abreviación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Tipos de Estado Civil',
                'db_table': 'cat_estado_civil',
            },
        ),
        migrations.CreateModel(
            name='CatGenero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('abreviacion', models.CharField(max_length=5, verbose_name='Abreviación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'db_table': 'cat_genero',
            },
        ),
        migrations.CreateModel(
            name='CatNivelEducativo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('abreviacion', models.CharField(max_length=5, verbose_name='Abreviación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Niveles educativos',
                'db_table': 'cat_nivel_educativo',
            },
        ),
        migrations.CreateModel(
            name='CatPoblacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('abreviacion', models.CharField(max_length=5, verbose_name='Abreviación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Población',
                'verbose_name_plural': 'Tipos Población',
                'db_table': 'cat_poblacion',
            },
        ),
    ]
