# Generated by Django 5.1.3 on 2025-03-18 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='nombre imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='temp/')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('grupal', models.BooleanField(default=False, null=True, verbose_name='imagen grupal')),
                ('id_respuesta', models.IntegerField(null=True, verbose_name='respuesta')),
                ('pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_preguntas', to='cuestionario.preguntamodel')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imagenes',
                'db_table': 'imagen_url',
            },
        ),
    ]
